### ISSUE TITLE
What do I need to set `service_token_cache_root_url` to?

### ISSUE THREAD

**Issue by phuesler** [ministryofjustice/fb-jwt-auth#12]
Hi,

what is facebooks base URL to retrieve the public keys with which they signed the token? So far I found [this](https://developers.facebook.com/docs/facebook-login/limited-login/token/) and I'm guessing it should be https://www.facebook.com/.well-known/oauth/openid/jwks/ . Is that correct?

So for production I would configure:

```
Fb::Jwt::Auth.configure do |config|
  # Service token cache domain
  #
  config.service_token_cache_root_url = 'https://www.facebook.com/.well-known/oauth/openid/jwks/'
end
```

Thank you for your work. Have a nice day.

**Comment by brenetic** [comment]
hi @phuesler,

we're not affiliated with facebook. this gem is used by the Ministry of Justice Forms product.

based on their docs i think that is indeed the correct endpoint to get the required public keys.

will close this for now. thanks

**Comment by phuesler** [comment]
thank you for the quick reply. By looking at the code, I'm guessing you have a proxy server in between that acts as a cache, therefore the application never talks directly to facebook. Have a nice day.
